### PR TITLE
Fixed text formatting bug

### LINKED ISSUE #1: Bug with text styling (bold, cursive, etc)
The notepad has a bug with text styling.

----
Steps to reproduce the bug:

 - Write a few lines of any text
 - Select any part of it
 - Go to the main menu and choose <kbd>Edit -> Bold/Cursive/Normal</kbd>
 - Repeat these steps a few more times

You will notice it does not work as it should.

Hint: take a look at `public/js/helpers.js` file, especially at `function setFontFormat(elem)`

### PR DESCRIPTION
**Pull request by shikhar13012001**
Sir, I have made a fix to text styling issue please review my PR and tell me if you need any changes.
(It took me a bit longer than expected to make it work properly;) )

### CODE REVIEW

**Comment by zaxovaiko** [comment]
@shikhar13012001, I have checked your commit. Well done! The issue is gone. The only thing is you should remove all `console.log` from the code. Do that and I will merge PR.

**Review by zaxovaiko — CHANGES_REQUESTED** [review]
Please, delete all `console.log`.

**Comment by shikhar13012001** [comment]
@zaxoavoki  sir I have removed all the log statements please review and tell me if you need any more changes, thankyou

**Comment by zaxovaiko** [comment]
@shikhar13012001, good job. Thanks :)

**Comment by shikhar13012001** [comment]
Thank you , Could you also add ```hacktoberfest-accepted``` label 😅😅😅that would be great

**Pull request merged**
